import type { Metadata } from "next";
import { Geist, Geist_Mono, Press_Start_2P } from "next/font/google";
import "./globals.css";
import { InputLogProvider } from "./components/InputLog";
import { InputLogSidebarShell } from "./components/InputLogSidebarShell";
import type { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pressStart = Press_Start_2P({
  variable: "--font-pixel",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${pressStart.variable}`}
    >
      <body className="antialiased">
        <InputLogProvider>
          <div className="retro-bg relative min-h-screen overflow-hidden font-sans text-zinc-50">
            {/* CRT overlay */}
            <div
              aria-hidden="true"
              className="pointer-events-none absolute inset-0 opacity-70 [background:repeating-linear-gradient(to_bottom,rgba(255,255,255,0.05),rgba(255,255,255,0.05)_1px,transparent_1px,transparent_3px)]"
            />
            <div
              aria-hidden="true"
              className="pointer-events-none absolute inset-0 opacity-40 [background:radial-gradient(ellipse_at_center,rgba(16,185,129,0.16)_0%,transparent_60%)]"
            />
            <InputLogSidebarShell>{children}</InputLogSidebarShell>
          </div>
        </InputLogProvider>
      </body>
    </html>
  );
}
